- hosts: k8s-all
  become: true
  gather_facts: false
  tasks:
  - name: Set hostname
    hostname: name='{{ inventory_hostname}}.{{ domain_name }}'
    
  - name: Updating /etc/hosts
    copy: 
      content: |
        127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
        ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
        {% for host in groups['k8s-all'] %}
        {{ hostvars[host].ansible_host }}   {{ hostvars[host].inventory_hostname }}.{{ domain_name }}  {{ hostvars[host].inventory_hostname }}
        {% endfor %}
      dest: /etc/hosts

