all:
    vars:
        ansible_ssh_user: centos
        ansible_become: true
        private_domain: 'ocp.local'
        public_domain: 'labcloud.litf4'
        ansible_private_key_file: 'key'
        api_subnet_cidr: 100.0.0.0/24
    children:
         local: { hosts: { 127.0.0.1: }}
         etcd: { children: { masters: }}
         glusterfs_registry: { children: { glusterfs: }}
         dns_servers: { children: { management: }}
         lb: { children: { infra: }}
         OSEv3:
            children:
                masters:
                nodes:
                etcd:
                lb:
                local:
                glusterfs:
                glusterfs_registry:
            vars:
                openshift_master_cluster_method: native
                openshift_master_cluster_hostname: 'cluster.{{ private_domain }}'
                openshift_master_cluster_public_hostname: 'ocp.{{ public_domain }}'
                openshift_master_default_subdomain: 'apps.{{ public_domain }}'
                openshift_master_cluter_ip: 100.0.0.26
                openshift_master_cluster_public_ip: 10.189.132.44
                openshift_deployment_type: origin
                os_sdn_network_plugin_name: 'redhat/openshift-ovs-multitenant'
                openshift_hosted_registry_storage_volume_size: 30Gi
                openshift_storage_glusterfs_registry_storageclass: True
                local_dns: 100.0.0.16
                external_interface: bond0

                openshift_disable_check:
                  - docker_image_availability
                  - memory_availability
                openshift_storage_glusterfs_namespace: app-storage
                openshift_storage_glusterfs_storageclass_default: false
                openshift_storage_glusterfs_block_deploy: true
                openshift_storage_glusterfs_block_host_vol_size: 100
                openshift_storage_glusterfs_block_storageclass: true
                openshift_storage_glusterfs_block_storageclass_default: false
                openshift_storage_glusterfs_is_native: false
                openshift_storage_glusterfs_heketi_is_native: true
                openshift_storage_glusterfs_heketi_executor: ssh
                openshift_storage_glusterfs_heketi_ssh_port: 22
                openshift_storage_glusterfs_heketi_ssh_user: centos
                openshift_storage_glusterfs_heketi_ssh_sudo: true
                openshift_storage_glusterfs_heketi_ssh_keyfile: "/root/deploy/openshift-ansible/key"
                openshift_hosted_registry_storage_kind: glusterfs
                openshift_hosted_registry_selector: 'node-role.kubernetes.io/infra=true'

                openshift_storage_glusterfs_registry_namespace: infra-storage
                openshift_storage_glusterfs_registry_block_deploy: true
                openshift_storage_glusterfs_registry_block_storageclass: true
                openshift_storage_glusterfs_registry_block_storageclass_default: false
                openshift_storage_glusterfs_registry_block_host_vol_size: 20
                openshift_master_ldap_ca_file: '/tmp/freeipa-cacert.p12'
                openshift_master_identity_providers:
                  - name: FreeIPA
                    challenge: true
                    login: true
                    kind: LDAPPasswordIdentityProvider
                    attributes:
                        id: ['dn']
                        email: ['mail']
                        name: ['cn']
                        preferredUsername: ['uid']
                    bindDN: 'uid=freeipabind,cn=users,cn=accounts,dc=labcloud,dc=litf4'
                    bindPassword: 'oZP3Z8D+PGjECUQWfc/YN4I9+UA='
                    insecure: false
                    # ca: freeipa-cacert.p12
                    url: 'ldap://freeipa.labcloud.litf4:389/cn=users,cn=accounts,dc=labcloud,dc=litf4?uid?sub?(&(!(memberOf=cn=disabledusers,cn=groups,cn=accounts,dc=labcloud,dc=litf4))(|(memberOf=cn=openshiftusers,cn=groups,cn=accounts,dc=labcloud,dc=litf4)(memberOf=cn=openshiftadmins,cn=groups,cn=accounts,dc=labcloud,dc=litf4)))'

         masters:
             hosts:
                master1: { ansible_host: 10.189.132.45 , openshift_ip: 100.0.0.18 , openshift_hostname: 'master1.{{ private_domain }}' }
                master2: { ansible_host: 10.189.132.29 , openshift_ip: 100.0.0.25 , openshift_hostname: 'master2.{{ private_domain }}' }
                master3: { ansible_host: 10.189.132.47 , openshift_ip: 100.0.0.21 , openshift_hostname: 'master3.{{ private_domain }}' }
             vars:
                 containerized: true
                 openshift_schedulable: true
                 openshift_node_group_name: 'node-config-master'
         infra:
             hosts:
                infra1: { ansible_host: 10.189.132.53 , openshift_public_ip: 10.189.132.53 , openshift_ip: 100.0.0.28 , openshift_hostname: 'infra1.{{ private_domain }}' }
                infra2: { ansible_host: 10.189.132.51 , openshift_public_ip: 10.189.132.51 , openshift_ip: 100.0.0.14 , openshift_hostname: 'infra2.{{ private_domain }}' }
             vars:
                 containerized: true
                 openshift_schedulable: true
                 openshift_node_group_name: 'node-config-infra'
         app:
             hosts:
                app1: { ansible_host: 10.189.132.48 , openshift_ip: 100.0.0.17 , openshift_hostname: 'app1.{{ private_domain }}' }
                app2: { ansible_host: 10.189.132.46 , openshift_ip: 100.0.0.15 , openshift_hostname: 'app2.{{ private_domain }}' }
                app3: { ansible_host: 10.189.132.42 , openshift_ip: 100.0.0.23 , openshift_hostname: 'app3.{{ private_domain }}' }
             vars:
                 containerized: true
                 openshift_schedulable: true
                 openshift_node_group_name: 'node-config-compute'
         glusterfs:
             hosts:
                storage1: { ansible_host: 10.189.132.49 , glusterfs_ip: 200.0.0.18 , openshift_ip: 100.0.0.24 , openshift_hostname: 'storage1.{{ private_domain }}' }
                storage2: { ansible_host: 10.189.132.36 , glusterfs_ip: 200.0.0.16 , openshift_ip: 100.0.0.31 , openshift_hostname: 'storage2.{{ private_domain }}' }
                storage3: { ansible_host: 10.189.132.54 , glusterfs_ip: 200.0.0.12 , openshift_ip: 100.0.0.30 , openshift_hostname: 'storage3.{{ private_domain }}' }
             vars:
                 containerized: true
                 openshift_schedulable: true
                 openshift_node_group_name: 'node-config-infra'
                 glusterfs_devices: [ "/dev/vdc", "/dev/vde", "/dev/vdd" ]
                 storage_subnet_cidr: 200.0.0.0/24
         nodes:
             children:
                 masters:
                 infra:
                 app:
         management:
            hosts:
                bastion:
                    ansible_host: 10.189.132.43
                    openshift_ip: 100.0.0.16
                    openshift_hostname: 'bastion.{{ private_domain }}'

