all:
    vars:
        ansible_ssh_user: centos
        ansible_private_key_file: key
        ansible_become: True
        openshift_deployment_type: origin
        domain_name: openshift.local
        target_hosts: [ app_nodes, master_nodes, infra_nodes, storage_nodes, ]
        management_hosts: [ management, ]
    children:
        masters: { children: { master_nodes: }}
        etcd: { children: { master_nodes: }}
        glusterfs: { children: { storage_nodes: }}
        glusterfs_registry: { children: { storage_nodes: }}
        loadbalancers:
            children:
                management:
        OSEv3:
            children:
                master_nodes:
                app_nodes:
                etcd:
            vars:
                ansible_user: centos
                openshift_hosted_registry_storage_kind: glusterfs
#                openshift_release: 3.10
#                openshift_image_tag: v3.10
#                openshift_pkg_version: -3.10.0
                openshift_deployment_type: origin
        management:
            hosts:
                buildhost: { ansible_host: 10.189.132.22 }
        app_nodes:
            hosts:
                node1: { ansible_host: 10.189.132.34 }
                node2: { ansible_host: 10.189.132.32 }
                node3: { ansible_host: 10.189.132.11 }
            vars:
                openshift_node_group_name: "node-config-compute"
        master_nodes:
            hosts:
                master1: { ansible_host: 10.189.132.36 }
                master2: { ansible_host: 10.189.132.35 }
                master3: { ansible_host: 10.189.132.37 }
            vars:
                openshift_node_group_name: "node-config-master"
                openshift_schedulable: True
        infra_nodes:
            hosts:
                infra1: { ansible_host: 10.189.132.7 }
                infra2: { ansible_host: 10.189.132.10 }
                infra3: { ansible_host: 10.189.132.29 }
            vars:
                openshift_node_group_name: "node-config-infra"
        nodes:
            children:
                app_nodes:
                infra_nodes:
                master_nodes:
        storage_nodes:
            hosts:
                storage1: { ansible_host: 10.189.132.20 }
                storage2: { ansible_host: 10.189.132.27 }
                storage3: { ansible_host: 10.189.132.9 }
            vars:
                glusterfs_devices: [ "/dev/vdc", "/dev/vdb", "/dev/vdd" ]

