all:
    vars:
        ansible_ssh_user: centos
        ansible_become: true
        private_domain: 'ocp.local'
        public_domain: 'labcloud.litf4'
        ansible_private_key_file: 'key'
        api_subnet_cidr: 100.0.0.0/24
        storage_subnet_cidr: 200.0.0.0/24
    children:
         # local: { hosts: { 127.0.0.1: }}
         etcd: { children: { masters: }}
         glusterfs_registry: { children: { glusterfs: }}
         dns_servers: { children: { management: }}
         lb: { children: { infra: }}
         OSEv3:
            children:
                masters:
                nodes:
                etcd:
                lb:
                # local:
                glusterfs:
                glusterfs_registry:
            vars:
                ## openshift_logging_es_pvc_storage_class_name: glusterfs-storage-block
                openshift_metrics_cassandra_pvc_storage_class_name: glusterfs-storage-block
                ## openshift_logging_install_logging: true
                ## openshift_logging_es_pvc_dynamic: true
                ## openshift_metrics_install_metrics: true
                openshift_master_cluster_method: native
                ## openshift_metrics_cassandra_storage_type: dynamic
                openshift_master_cluster_hostname: 'console.{{ private_domain }}'
                openshift_master_cluster_public_hostname: 'ocp.{{ public_domain }}'
                openshift_master_default_subdomain: 'apps.{{ public_domain }}'
                openshift_master_cluster_ip: 100.0.0.21
                openshift_master_cluster_public_ip: 10.189.132.44
                openshift_deployment_type: origin
                os_sdn_network_plugin_name: 'redhat/openshift-ovs-multitenant'
                openshift_hosted_registry_storage_volume_size: 15Gi
                openshift_storage_glusterfs_registry_storageclass: True
                local_dns: 100.0.0.18

                openshift_disable_check:
                  - docker_image_availability
                  - memory_availability
                openshift_storage_glusterfs_namespace: app-storage
                openshift_storage_glusterfs_storageclass_default: false
                openshift_storage_glusterfs_block_deploy: true
                openshift_storage_glusterfs_block_host_vol_size: 100
                openshift_storage_glusterfs_block_storageclass: true
                openshift_storage_glusterfs_block_storageclass_default: false
                openshift_storage_glusterfs_is_native: false
                openshift_storage_glusterfs_heketi_is_native: true
                openshift_storage_glusterfs_heketi_executor: ssh
                openshift_storage_glusterfs_heketi_ssh_port: 22
                openshift_storage_glusterfs_heketi_ssh_user: centos
                openshift_storage_glusterfs_heketi_ssh_sudo: true
                openshift_storage_glusterfs_heketi_ssh_keyfile: "/root/deploy/openshift-ansible/key"
                openshift_hosted_registry_storage_kind: glusterfs
                openshift_hosted_registry_selector: 'node-role.kubernetes.io/infra=true'

                openshift_storage_glusterfs_registry_namespace: infra-storage
                openshift_storage_glusterfs_registry_block_deploy: true
                openshift_storage_glusterfs_registry_block_storageclass: true
                openshift_storage_glusterfs_registry_block_storageclass_default: false
                openshift_storage_glusterfs_registry_block_host_vol_size: 20
                openshift_master_ldap_ca_file: '/tmp/freeipa-cacert.p12'
                openshift_master_identity_providers:
                    - name: htpasswd_auth
                      login: true
                      challenge: true
                      kind: HTPasswdPasswordIdentityProvider
                      file: /etc/openshift/openshift-passwd

##                 openshift_master_identity_providers:
##                   - name: FreeIPA
##                     challenge: true
##                     login: true
##                     kind: LDAPPasswordIdentityProvider
##                     attributes:
##                         id: ['dn']
##                         email: ['mail']
##                         name: ['cn']
##                         preferredUsername: ['uid']
##                     bindDN: 'uid=freeipabind,cn=users,cn=accounts,dc=labcloud,dc=litf4'
##                     bindPassword: 'oZP3Z8D+PGjECUQWfc/YN4I9+UA='
##                     insecure: false
##                     # ca: freeipa-cacert.p12
##                     url: 'ldap://freeipa.labcloud.litf4:389/cn=users,cn=accounts,dc=labcloud,dc=litf4?uid?sub?(&(!(memberOf=cn=disabledusers,cn=groups,cn=accounts,dc=labcloud,dc=litf4))(|(memberOf=cn=openshiftusers,cn=groups,cn=accounts,dc=labcloud,dc=litf4)(memberOf=cn=openshiftadmins,cn=groups,cn=accounts,dc=labcloud,dc=litf4)))'

         masters:
             hosts:
                master1:
                    openshift_hostname: 'master1.{{ private_domain }}'
                    ansible_host: 10.189.132.50
                    openshift_ip: 100.0.0.27
                    glusterfs_ip: 200.0.0.25
                master2:
                    openshift_hostname: 'master2.{{ private_domain }}'
                    ansible_host: 10.189.132.51
                    openshift_ip: 100.0.0.14
                    glusterfs_ip: 200.0.0.24
                master3:
                    openshift_hostname: 'master3.{{ private_domain }}'
                    ansible_host: 10.189.132.56
                    openshift_ip: 100.0.0.30
                    glusterfs_ip: 200.0.0.15
             vars:
                 containerized: true
                 openshift_schedulable: true
                 openshift_node_group_name: 'node-config-master'
         infra:
             hosts:
                app1: { ansible_host: 10.189.132.62 , openshift_ip: 100.0.0.19 , openshift_hostname: 'app1.{{ private_domain }}', glusterfs_ip: 200.0.0.16  }
                app2: { ansible_host: 10.189.132.60 , openshift_ip: 100.0.0.26 , openshift_hostname: 'app2.{{ private_domain }}', glusterfs_ip: 200.0.0.18  }
##             children:
##                 app[1-2]:
##             hosts:
##                 infra1:
##                     openshift_hostname: 'app1.{{ private_domain }}'
##                     ansible_host: 10.189.132.62
##                     openshift_public_ip: 100.0.0.19
##                     openshift_ip: 100.0.0.19
##                     glusterfs_ip: 200.0.0.16
##                 infra2:
##                     openshift_hostname: 'app2.{{ private_domain }}'
##                     ansible_host: 10.189.132.60
##                     openshift_public_ip: 10.189.132.60
##                     openshift_ip: 100.0.0.26
##                     glusterfs_ip: 200.0.0.18

             vars:
                 containerized: true
                 openshift_schedulable: true
                 openshift_node_group_name: 'node-config-infra'
                 public_vips: [ 10.189.132.43 , 10.189.132.48 ]
         app:
             hosts:
                app1: { ansible_host: 10.189.132.62 , openshift_ip: 100.0.0.19 , openshift_hostname: 'app1.{{ private_domain }}', glusterfs_ip: 200.0.0.16  }
                app2: { ansible_host: 10.189.132.60 , openshift_ip: 100.0.0.26 , openshift_hostname: 'app2.{{ private_domain }}', glusterfs_ip: 200.0.0.18  }
                app3: { ansible_host: 10.189.132.63 , openshift_ip: 100.0.0.23 , openshift_hostname: 'app3.{{ private_domain }}', glusterfs_ip: 200.0.0.20  }
                app4: { ansible_host: 10.189.132.64 , openshift_ip: 100.0.0.17 , openshift_hostname: 'app4.{{ private_domain }}', glusterfs_ip: 200.0.0.13  }
                app5: { ansible_host: 10.189.132.46 , openshift_ip: 100.0.0.20 , openshift_hostname: 'app5.{{ private_domain }}', glusterfs_ip: 200.0.0.22  }
             vars:
                 containerized: true
                 openshift_schedulable: true
                 openshift_node_group_name: 'node-config-compute'
         glusterfs:
             hosts:
                storage1: { ansible_host: 10.189.132.53 , glusterfs_ip: 200.0.0.26 , openshift_ip: 100.0.0.15 , openshift_hostname: 'storage1.{{ private_domain }}' }
                storage2: { ansible_host: 10.189.132.61 , glusterfs_ip: 200.0.0.23 , openshift_ip: 100.0.0.29 , openshift_hostname: 'storage2.{{ private_domain }}' }
                storage3: { ansible_host: 10.189.132.55 , glusterfs_ip: 200.0.0.14 , openshift_ip: 100.0.0.25 , openshift_hostname: 'storage3.{{ private_domain }}' }
             vars:
                 containerized: true
                 openshift_schedulable: true
                 openshift_node_group_name: 'node-config-infra'
                 glusterfs_devices: [ "/dev/vdc", "/dev/vde", "/dev/vdd" ]
         nodes:
             children:
                 masters:
                 infra:
                 app:
         management:
            hosts:
                bastion:
                    ansible_host: 10.189.132.40
                    openshift_ip: 100.0.0.18
                    openshift_hostname: 'bastion.{{ private_domain }}'

# Find the private key in ocp31.key
