all:
    vars:
        ansible_ssh_user: centos
        ansible_private_key_file: key
        ansible_become: True
        openshift_deployment_type: origin
        domain_name: novalocal
        target_hosts: [ app_nodes, master_nodes, infra_nodes, storage_nodes, ]
        management_hosts: [ management, ]
    children:
        masters: { children: { master_nodes: }}
        etcd: { children: { master_nodes: }}
        glusterfs: { children: { storage_nodes: }}
        glusterfs_registry: { children: { storage_nodes: }}
        OSEv3:
            children:
                master_nodes:
                app_nodes:
                etcd:
            vars:
                ansible_user: centos
                openshift_hosted_registry_storage_kind: glusterfs
                openshift_deployment_type: origin
                openshift_disable_check:
                  - docker_image_availability
                  - memory_availability
                  - disk_availability
                  - package_availability
                  - package_version
        dns_servers:
            hosts:
                dns_server: { ansible_host: 10.189.132.32 }
        loadbalancer_nodes:
            children:
                management:
        management:
            hosts:
                buildhost: { ansible_host: 10.189.132.11 }
        lb:
            children:
                loadbalancer_nodes:
        app_nodes:
            hosts:
                node1: { ansible_host: 10.189.132.35 }
                node2: { ansible_host: 10.189.132.28 }
                node3: { ansible_host: 10.189.132.10 }
            vars:
                openshift_node_group_name: "node-config-compute"
        master_nodes:
            hosts:
                master1: { ansible_host: 10.189.132.36 }
                master2: { ansible_host: 10.189.132.40 }
                master3: { ansible_host: 10.189.132.7 }
            vars:
                openshift_node_group_name: "node-config-master"
                openshift_schedulable: True
        infra_nodes:
            hosts:
                infra1: { ansible_host: 10.189.132.33 }
                infra2: { ansible_host: 10.189.132.21 }
                infra3: { ansible_host: 10.189.132.34 }
            vars:
                openshift_node_group_name: "node-config-infra"
        nodes:
            children:
                app_nodes:
                infra_nodes:
                master_nodes:
        storage_nodes:
            hosts:
                storage1: { ansible_host: 10.189.132.9 }
                storage2: { ansible_host: 10.189.132.20 }
                storage3: { ansible_host: 10.189.132.29 }
            vars:
                glusterfs_devices: [ "/dev/vdc", "/dev/vdb", "/dev/vdd" ]

