- hosts: ocp_nodes,buildhost,storage_nodes
  become: true
  gather_facts: false
  tasks:
  - name: Set hostname
    hostname: name='{{ inventory_hostname}}.{{ domain_name }}'

  - name: Disable swap
    shell: "swapoff /dev/vdb || true"

  - name: Updating /etc/hosts
    copy:
      content: |
        127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
        ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
        {% for host in groups['ocp_nodes'] %}
        {{ hostvars[host].ansible_host }}   {{ hostvars[host].inventory_hostname }}.{{ domain_name }}  {{ hostvars[host].inventory_hostname }}
        {% endfor %}
      dest: /etc/hosts


  - name: Set exporting Kubeconf in shell
    lineinfile:
        path: ~/.bashrc
        regexp: '^export\ KUBECONFIG=.*$'
        line: 'export KUBECONFIG=/etc/kubernetes/admin.conf'

  - name: Set .vimrc 
    copy:
        dest: $HOME/.vimrc
        content: |
            set expandtab
            set number
            set tabstop=4
            set shiftwidth=4
            syntax on
            "colorscheme elflord
        mode: '0644'

