- hosts: 
    - masters
    - nodes
    - infra
    - glusterfs
    - glusterfs_registry
    - etcd
    - app
    - bastion
  become: true
  tags:
    - master_nodes
    - infra_nodes
    - app_nodes
    - all
  gather_facts: false
  tasks:



  - name: Install updates
    package: name='*' state=latest

  - name: Install required packages
    package: name='{{ item }}'
    with_items:
      - NetworkManager
      - wget
      - git
      - net-tools
      - bind-utils
      - yum-utils
      - iptables-services
      - bridge-utils
      - bash-completion
      - kexec-tools
      - sos
      - psacct
      - docker
      - glusterfs-fuse

  - name: Installing httpd-tools on bastion
    package: name='{{ item }}'
    with_items:
    - httpd-tools
    - java-1.8.0-openjdk-headless
    - python2-pip
    - python-devel
    - gcc
    when: inventory_hostname == 'bastion'

  - name: Install httpd-tools
    yum: name=httpd-tools state=present
    when: inventory_hostname in groups['masters']

  - name: Ensure NetworkManager
    service: name=NetworkManager state=started enabled=on

