- hosts: all
  become: true
  gather_facts: false
  tasks:

  - name: Set hostname
    hostname: name='{{ inventory_hostname }}.{{ domain_name }}'

  - name: Reboot hosts
    shell: "sleep 5 && reboot"
    async: 1
    poll: 0

  - name: Wait for the reboot to complete
    wait_for_connection:
        connection_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300

