- hosts:
    - masters
    - nodes
    - infra
    - glusterfs
    - glusterfs_registry
    - etcd
    - app
    - bastion
  become: true
  gather_facts: false
  tasks:
  - name: Creating ifcfg-eth1 config
    copy: 
        content: |
            BOOTPROTO=none
            DEVICE=eth1
            ONBOOT=yes
            TYPE=Ethernet
            {% if openshift_ip is defined %}
            IPADDR={{ openshift_ip }}
            {% endif %}
            NETMASK=255.255.255.0
        dest: /etc/sysconfig/network-scripts/ifcfg-eth1
        mode: '0644'
    notify:
    - restart_eth1

  handlers:
  - name: restart_eth1
    shell: "ifdown eth1 && ifup eth1"
     


