- hosts: all
  become: false 
  gather_facts: no
  tasks:

  - name: Add a host in the '{{ service_nodes_group_name }}' group
    add_host: 
        name: '{{ item }}'
        groups: '{{ service_nodes_group_name }}'
    with_items: groups[service_nodes_group_name]

