- hosts:
    - masters
    - infra
    - app
  become: true
  gather_facts: false
  tasks:
  - name: Install CA certificate
    copy:
        src: files/redhat-uep.pem
        dest: /etc/rhsm/ca/redhat-uep.pem
        
