- hosts: 
    - management
  become: false
  gather_facts: false
  tags:
    - management
  vars: 
    deploy_dir: ~/deploy
    openshift_ansible_localdir: '{{ deploy_dir }}/openshift-ansible'
    openshift_ansible_repo: 'https://github.com/openshift/openshift-ansible'
    openshift_ansible_version: release-3.10
    inventory_file: 'hosts.yml'
    ssh_priv_key_file: 'key'

  tasks:

  - name: Create Deploy_dir
    file:
        path: '{{ deploy_dir }}'
        state: directory

  - name: Install Git
    yum: name=git state=present
    
  - name: Get Openshift-Ansible
    git:
        dest: '{{ openshift_ansible_localdir }}'
        repo: '{{ openshift_ansible_repo }}'
        force: true
        version: '{{ openshift_ansible_version }}' 

  - name: Copy Inventory
    copy:
        src: '../{{ inventory_file }}'
        dest: '{{ openshift_ansible_localdir }}/{{ inventory_file }}'
  
  - name: Copy Private Key file
    copy:
        src: '../{{ ssh_priv_key_file }}'
        dest: '{{ openshift_ansible_localdir }}/{{ ssh_priv_key_file }}'
        mode: '0400'

