- hosts: 
    - management
  become: false
  gather_facts: false
  tags:
    - management
  tasks:

  - name: Install Epel-Release
    yum: name=epel-release state=present

  - name: Install Updates
    yum: name='*' state=latest

  - name: Install Ansible
    yum: name='{{ item }}' state=present
    with_items: 
     - ansible
     - git

