- hosts: all
  become: true
  gather_facts: false
  tags:
    - all
  tasks:

  - name: Set /etc/hosts
    copy: 
        content: |
            127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
            ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
            {% for h in groups['all'] %}
            {{ hostvars[h].ansible_host }}  {{ h }}.{{ domain_name }}  {{ h }}  {{ h }}.novalocal
            {% endfor %}
        dest: /etc/hosts

  - name: Set hostname
    hostname: name='{{ inventory_hostname }}.{{ domain_name }}'

  - name: Reboot hosts
    shell: "sleep 5 && reboot"
    async: 1
    poll: 0
 
  - name: Wait for the reboot to complete
    connection_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300

- hosts: master_nodes,infra_nodes,app_nodes
  become: true
  gather_facts: false
  tasks:

  - name: Install updates
    yum: name="{{ item }}" state=present
    with_items:
    - '*'

  - name: Install NetworkManager
    yum: name="{{ item }}" state=present
    with_items:
    - NetworkManager


  - name: Install dependencies
    yum: name='{{ item }}' state=present
    with_items:
      - wget
      - git
      - net-tools
      - bind-utils
      - yum-utils
      - iptables-services
      - bridge-utils
      - bash-completion
      - kexec-tools
      - sos
      - psacct
      - docker

  - name: Ensure NetworkManager
    service: name=NetworkManager enabled=on state=started


- hosts: management
  become: false
  gather_facts: false
  tags: 
  - management
  tasks:

   - name: Install Epel
     yum: name=epel-release

   - name: Install Ansible
     yum: name=ansible state=present

   - name: Install Git
     yum: name=git state=present

   - name: Make an installation directory
     file:
        path: ~/deploy
        state: directory

   - name: Clone Git repository
     git:
        dest: ~/deploy/openshift-ansible
        repo: https://github.com/openshift/openshift-ansible
        version: release-3.10
        
   - name: Copy some files to deploy host
     copy:
        src: '{{ item.from }}'
        dest: '~/deploy/{{ item.to }}'
        mode: '0600'
        force: true
     with_items:
        - { from: "key", to: "openshift-ansible/key" }
        - { from: "hosts.yml", to: "openshift-ansible/hosts.yml" }

   - name: Update ansible.cfg to point at right inventory
     lineinfile: 
        path: ~/deploy/openshift-ansible/ansible.cfg
        regexp: '^.*\ inventory\ =.*$'
        line: 'inventory = hosts.yml'
 
