- hosts: glusterfs
  become: true
  gather_facts: false
  tasks:

  - name: Stop glusterd service
    service: name=glusterd state=stopped

  - name: Clean up /var/lib/glusterd directory
    shell: "rm -rf /var/lib/glusterd/* || true"

  - name: Executing wipefs on '{{ glusterfs_devices }}'
    command: /usr/sbin/wipefs --all --force '{{ item }}'
    loop: '{{ glusterfs_devices }}'

