- hosts: storage_nodes
  become: true
  gather_facts: false
  tasks:

  - name: Enable all incoming packets
    iptables: 
        chain: INPUT
        protocol: '{{ item.proto }}'
        jump: ACCEPT
        source: '0.0.0.0/0'
    loop:
    - { proto: icmp }
    - { proto: tcp }
    - { proto: udp }

