- hosts:
    - infra
    - masters
    - app
  become: true
  gather_facts: false
  tasks:
  - name: Creating ifcfg-eth2 config
    copy: 
        content: |
            BOOTPROTO=none
            DEVICE=eth2
            ONBOOT=yes
            TYPE=Ethernet
            IPADDR={{ glusterfs_ip }}
            NETMASK={{ storage_subnet_cidr | ipaddr('netmask') }}
        dest: /etc/sysconfig/network-scripts/ifcfg-eth2
        mode: '0644'
    when: glusterfs_ip is defined
    notify:
    - restart_eth2

  handlers:
  - name: restart_eth2
    shell: "ifdown eth2 && ifup eth2"
     


