- hosts:
  - lb
  - nodes
  become: true
  gather_facts: false
  tasks:

  - name: Copy file(s)
    copy:
      src: '{{ item }}'
      dest: ~/
    loop:
    - '../ansible.cfg'
    - '../inventory.yml'
    when: inventory_hostname in groups['lb']

  - name: Copy /etc/hosts
    copy:
      content: |
        127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
        ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
        
        {% for host in groups['nodes'] + groups['lb'] %}
        {{ hostvars[host].openshift_ip }} {{ hostvars[host].openshift_hostname }} {{ host }}
        {% endfor %}

      dest: /etc/hosts

  - name: Create directory /etc/origin/master
    file:
      path: /etc/origin/master
      state: directory
      recurse: true

  - name: Copy openshift  users
    copy:
      content: '{{ htusers }}'
      dest: '{{ openshift_master_identity_providers.0.filename }}'

  - name: Install ansible
    yum: name=ansible state=latest
    when: inventory_hostname in groups['lb']

