---
- hosts:
  - lb
  - masters
  - nodes
  gather_facts: true
  become: true
  pre_tasks:

  roles:
    - name: '../roles/bootstrap'
      dev_name: '{{ net2_devname }}'
      dev_netmask: '{{ net2_netmask }}'
      dev_ip: '{{ net2_ip }}' 
      dns_ip: '{{ hostvars["lb.ocp.local"].net2_ip }}'
      domain_name: '{{ cluster_domain_name }}'
      dns_servers_group_name: 'lb'
      lb_servers_group_name: 'lb'

  
